import type { TrainingModule } from "../model";
import { SOURCES } from "../sources";

export const shift: TrainingModule = {
  id: "shift",
  title: "Your First Shift",
  mapLabel: "Final Site Challenge",
  description: "A full morning on the fictional yard. The debrief comes at the end, not after each call.",
  estimatedMinutes: 20,
  difficulty: "Field",
  completionXp: 500,
  jurisdiction: "CANADA",
  warnings: ["site-specific"],
  badgeId: "site-ready",
  notes: [
    {
      jurisdiction: "ALBERTA",
      body: "Alberta detail you saw earlier still applies, and so do the limits. This shift is a scene, not an orientation for a real Northline yard and not a certificate.",
    },
  ],
  objectives: [
    "Make a full set of site decisions without being told the answer in the moment.",
    "See which skills carried the morning and which modules to open again.",
  ],
  sources: [
    SOURCES.albertaOhs,
    SOURCES.hierarchy,
    SOURCES.pictograms,
    SOURCES.labels,
    SOURCES.sds,
    SOURCES.albertaFall,
  ],
  blocks: [
    {
      type: "lesson",
      id: "shift-learn",
      phase: "learn",
      xpKind: "lesson",
      title: "Clock in",
      paragraphs: [
        "You are on a simulated shift at Northline Yard. Nobody will mark your answers until the debrief. A logged decision is not a hint.",
        "The yard is fictional. The habits are the ones the earlier modules practised: gear, hazards, tools, products, talk, emergencies, and reports.",
      ],
      callout: {
        title: "No speed bonus",
        body: "Take the time you need. Finishing the shift faster does not raise the score.",
      },
    },
    {
      type: "shift",
      id: "shift-sim",
      phase: "play",
      xpKind: "challenge",
      title: "The shift",
      intro: "Eight moments. Log each one. The debrief sorts them after you clock out.",
      beats: [
        {
          id: "gate-ppe",
          kicker: "06:52 · Gate",
          prompt: "Your hard hat is still in the truck. The gate attendant says you’ll only be inside for a minute.",
          detail: "The yard rule you were given says hard hats inside the fence.",
          dimension: "decision",
          reviewModuleId: "ppe",
          options: [
            { id: "in", label: "Go in. A minute doesn’t count.", quality: "unsafe", review: "The yard rule was already set. A minute inside is still inside." },
            { id: "hat", label: "Go back for the hard hat, then sign in.", quality: "strong", review: "You followed the yard rule before you needed a reason." },
            { id: "cap", label: "Borrow a baseball cap from the attendant.", quality: "weak", review: "A cap is not the hard hat the yard required." },
          ],
        },
        {
          id: "cable",
          kicker: "07:10 · Corridor",
          prompt: "A cable runs across the only doorway people are using.",
          detail: "You can see a clip point on the wall that would get it off the floor.",
          dimension: "hazard",
          reviewModuleId: "hazards",
          options: [
            { id: "over", label: "Step over it and keep going.", quality: "unsafe", review: "The next person, carrying something, will not step cleanly." },
            { id: "deal", label: "Stop, get the cable off the walkway, and tell the supervisor it was across the door.", quality: "strong", review: "You removed the trip and reported the setup." },
            { id: "kick", label: "Kick it to the side without looking at where it lands.", quality: "weak", review: "It may now be a trip in a darker spot, or a tug on a live tool." },
          ],
        },
        {
          id: "lift-talk",
          kicker: "07:25 · Slab",
          prompt: "You did not hear the lift plan. The load is about to move.",
          detail: "The signal person is looking at you as if you already agreed.",
          dimension: "communication",
          reviewModuleId: "conduct",
          options: [
            { id: "nod", label: "Nod. You’ll pick it up as it happens.", quality: "unsafe", review: "A nod starts the lift on a plan you don’t have." },
            { id: "again", label: "Stop it and ask them to say your part again.", quality: "strong", review: "Clarify before the load moves." },
            { id: "after", label: "Ask another worker what you missed after the lift starts.", quality: "weak", review: "After is too late to be in the wrong place." },
          ],
        },
        {
          id: "grinder",
          kicker: "08:05 · Bench",
          prompt: "The grinder you were handed has the guard removed.",
          detail: "A newer worker says they can “just be careful” with it.",
          dimension: "procedure",
          reviewModuleId: "tools",
          options: [
            { id: "use", label: "Use it. The cut is small.", quality: "unsafe", review: "Small cuts still throw a wheel." },
            { id: "note", label: "Tape a note to it and use it anyway.", quality: "unsafe", review: "A note is not a guard." },
            { id: "tag", label: "Take it out of service and tell the supervisor. Don’t hand it to the new worker.", quality: "strong", review: "Out of service, reported, and not passed along." },
          ],
        },
        {
          id: "bottle",
          kicker: "09:00 · Cage",
          prompt: "An unlabelled bottle is on the adhesive shelf. A coworker says it smells like the usual solvent.",
          detail: "The SDS binder for the labelled products is on the wall.",
          dimension: "knowledge",
          reviewModuleId: "whmis",
          options: [
            { id: "sniff", label: "Sniff it yourself to confirm.", quality: "unsafe", review: "Smell is an exposure, not a label." },
            { id: "use", label: "Use it. The shelf is the clue.", quality: "unsafe", review: "A shelf is not a product identifier." },
            { id: "leave", label: "Leave it closed and check with the supervisor before anyone uses it.", quality: "strong", review: "Unlabelled product stays unused until it is identified." },
          ],
        },
        {
          id: "scrap",
          kicker: "10:15 · Stair",
          prompt: "Offcuts are piled against the extinguisher at the stair.",
          detail: "You can move them without blocking the stair or the door.",
          dimension: "procedure",
          reviewModuleId: "report",
          options: [
            { id: "not-mine", label: "Leave it. Another trade made the mess.", quality: "weak", review: "The extinguisher doesn’t care which trade blocked it." },
            { id: "move", label: "Move the offcuts clear, then tell the supervisor what you found.", quality: "strong", review: "You fixed what you could and you reported it." },
            { id: "behind", label: "Tuck the pile behind the extinguisher so the stair looks clean.", quality: "unsafe", review: "Hidden and blocked are the same." },
          ],
        },
        {
          id: "alarm",
          kicker: "11:40 · Alarm",
          prompt: "The site alarm sounds. You are mid-cut. Your phone is in the trailer.",
          detail: "You were shown the east stair and the muster sign by the gate.",
          dimension: "procedure",
          reviewModuleId: "emergency",
          options: [
            { id: "cut", label: "Finish the cut. It’s probably a drill.", quality: "unsafe", review: "The alarm is the instruction to leave." },
            { id: "copy", label: "Watch what the far crew does and stay if they stay.", quality: "weak", review: "Another crew’s hesitation is not the plan." },
            { id: "out", label: "Stop, take the east stair, and muster at the gate.", quality: "strong", review: "Route and muster. The phone stays in the trailer." },
          ],
        },
        {
          id: "told",
          kicker: "12:10 · After",
          prompt: "Earlier you moved a loose board out of a doorway. You were allowed to pick it up. Nobody was hurt.",
          detail: "The same doorway had scrap in it yesterday.",
          dimension: "communication",
          reviewModuleId: "report",
          options: [
            { id: "nothing", label: "Say nothing. It’s handled.", quality: "weak", review: "The pattern stays invisible if you only fix it." },
            { id: "tell", label: "Tell the supervisor what you found, what you did, and that it happened yesterday too.", quality: "strong", review: "A short report turns a repeated trip into something the site can stop." },
            { id: "lunch", label: "Joke about it at lunch and leave it there.", quality: "weak", review: "The lunch table is not the hazard report." },
          ],
        },
      ],
    },
  ],
};
