import type { HazardSpot, TrainingModule } from "../model";
import { SOURCES } from "../sources";

const storageHazards: HazardSpot[] = [
  {
    id: "incompatible",
    kind: "jug",
    x: 22,
    y: 42,
    label: "Solvent stored against an acid",
    feedback: "Two products that should not sit together are touching. Incompatible storage is a chemical hazard even when both labels are on.",
    severity: "high",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "A reaction between incompatibles can be sudden. This is not low." },
      { id: "moderate", label: "Moderate", correct: false, feedback: "Treat incompatibles as a high concern until someone who knows the products separates them." },
      { id: "high", label: "High", correct: true, feedback: "High. Separation is the control, using the SDS, not a guess about which shelf “feels right.”" },
    ],
    controlPrompt: "What do you do?",
    controlOptions: [
      { id: "separate", label: "Leave them closed, keep people back, and get the supervisor so they are separated using the SDS", correct: true, feedback: "Don’t improvise a chemical move you were not trained for. Report it and keep the containers closed." },
      { id: "mix", label: "Pour one into the other to save shelf space", correct: false, feedback: "Mixing unknowns, or even known incompatibles, is how incidents start." },
      { id: "ignore", label: "Leave them. They have labels, so storage is fine", correct: false, feedback: "A label tells you what it is. It does not mean the neighbour is compatible." },
    ],
  },
  {
    id: "cracked-drum",
    kind: "drum",
    x: 40,
    y: 62,
    label: "Cracked drum",
    feedback: "The drum wall is split. The product can leave the container.",
    severity: "high",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "A split drum is a release waiting to happen." },
      { id: "moderate", label: "Moderate", correct: false, feedback: "If product can escape, treat it as high and keep people off it." },
      { id: "high", label: "High", correct: true, feedback: "High. Stay out of the product and report the damaged container." },
    ],
    controlPrompt: "The drum is cracked.",
    controlOptions: [
      { id: "report", label: "Keep clear and report it. Do not transfer the product unless you are trained and the procedure says to", correct: true, feedback: "Damaged container, reported. Transfer is a task with its own PPE and procedure." },
      { id: "tape", label: "Tape the crack and keep using it", correct: false, feedback: "Tape is not a container." },
      { id: "tip", label: "Tip it so the crack is up and keep working", correct: false, feedback: "Moving a cracked drum can spill it on you." },
    ],
  },
  {
    id: "no-label",
    kind: "jug",
    x: 58,
    y: 36,
    label: "Container with no label",
    feedback: "Nothing on this container tells you the product, the hazard, or the supplier.",
    severity: "high",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "Unknown product is not low." },
      { id: "moderate", label: "Moderate", correct: false, feedback: "You cannot rate the contents. Treat the unknown as high until it is identified." },
      { id: "high", label: "High", correct: true, feedback: "High, because you cannot protect yourself from a product you cannot name." },
    ],
    controlPrompt: "There is no label.",
    controlOptions: [
      { id: "hold", label: "Do not use it. Report it so it can be identified or removed", correct: true, feedback: "No label, no use. WHMIS depends on people being able to identify the product." },
      { id: "smell", label: "Smell it and write a label from memory", correct: false, feedback: "Your nose is not a classification method, and the exposure is real." },
      { id: "use", label: "Use it. The shelf is the solvent shelf", correct: false, feedback: "Location is not a label. People put the wrong jug down all the time." },
    ],
  },
  {
    id: "sideways",
    kind: "stack",
    x: 74,
    y: 48,
    label: "Container on its side over the walkway",
    feedback: "A container is stored on its side, above the path, with the cap pointing out.",
    severity: "moderate",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "If the cap weeps, the product lands on whoever walks under it." },
      { id: "moderate", label: "Moderate", correct: true, feedback: "Moderate until it leaks, and it should still be moved by someone following the storage procedure." },
      { id: "high", label: "High", correct: false, feedback: "It is a bad store, and it is not yet a spreading spill. Report it before it becomes one." },
    ],
    controlPrompt: "How do you correct the storage?",
    controlOptions: [
      { id: "upright", label: "Keep people out from under it and tell the supervisor so it is stored upright, as the SDS allows", correct: true, feedback: "Upright, compatible, and not over a walkway. Don’t catch it with your hands if you were not told to move it." },
      { id: "leave", label: "Leave it. Gravity has not won yet", correct: false, feedback: "Waiting for the leak is the incident." },
      { id: "open", label: "Open it to reduce pressure", correct: false, feedback: "Opening it creates the exposure you are trying to avoid." },
    ],
  },
  {
    id: "spill",
    kind: "spill",
    x: 46,
    y: 78,
    label: "Spill on the floor",
    feedback: "Product is on the floor and spreading toward the aisle.",
    severity: "high",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "An unknown or labelled hazardous spill in a walkway is not low." },
      { id: "moderate", label: "Moderate", correct: false, feedback: "People can walk through it and track it. Treat it as high." },
      { id: "high", label: "High", correct: true, feedback: "High. Keep people out and follow the spill procedure for your level of training." },
    ],
    controlPrompt: "You are not on the spill team.",
    controlOptions: [
      { id: "back", label: "Step back, warn others, and report it. Check the SDS only from a safe place", correct: true, feedback: "Your job at this level is to avoid exposure and get the right people. Cleanup beyond your training is not heroism." },
      { id: "mop", label: "Mop it with whatever is by the sink", correct: false, feedback: "The wrong absorbent can spread it or react. The SDS and the site plan name the response." },
      { id: "fan", label: "Turn on a fan and keep working", correct: false, feedback: "A fan can push vapours toward other people." },
    ],
  },
  {
    id: "sds-locked",
    kind: "binder",
    x: 84,
    y: 30,
    label: "SDS binder locked away",
    feedback: "The SDS people need for these products is in a locked cabinet, and the key is off site.",
    severity: "moderate",
    severityOptions: [
      { id: "low", label: "Low", correct: false, feedback: "If nobody can open the SDS, nobody can check the controls." },
      { id: "moderate", label: "Moderate", correct: true, feedback: "Moderate as a system failure. It becomes worse the moment someone needs the sheet for a spill or for PPE." },
      { id: "high", label: "High", correct: false, feedback: "Call it a serious access problem and get it fixed today. The products themselves may be a separate high hazard." },
    ],
    controlPrompt: "Workers cannot get the SDS.",
    controlOptions: [
      { id: "access", label: "Tell the supervisor the SDS is not accessible and do not use the products until people can read it", correct: true, feedback: "SDS access is part of WHMIS. A binder nobody can open does not count." },
      { id: "memory", label: "Rely on what the crew remembers from last month", correct: false, feedback: "Memory is not an SDS. Products and procedures change." },
      { id: "skip", label: "Skip the products that look dangerous and use the rest", correct: false, feedback: "Looks are not a classification. Access comes first." },
    ],
  },
];

export const whmis: TrainingModule = {
  id: "whmis",
  title: "WHMIS: Chemical Detective",
  mapLabel: "WHMIS",
  description: "Read the label, find the SDS section you need, and don’t guess the product.",
  estimatedMinutes: 25,
  difficulty: "Field",
  completionXp: 500,
  jurisdiction: "CANADA",
  warnings: ["site-specific"],
  badgeId: "chemical-detective",
  notes: [
    {
      jurisdiction: "CANADA",
      body: "WHMIS supplier rules are federal, under the Hazardous Products Act and Hazardous Products Regulations. Worker education and site training are also an employer duty under provincial OHS law. This module is general education. It is not your employer’s WHMIS training on the products in your workplace.",
    },
    {
      jurisdiction: "ALBERTA",
      body: "In Alberta, that employer duty sits with the OHS legislation and the employer’s program.",
    },
  ],
  objectives: [
    "Recognize WHMIS pictograms and say what kind of harm they signal.",
    "Find the product identifier, pictogram, signal word, hazard statement, precautionary statements, and supplier information on a label.",
    "Open the SDS section that answers the question in front of you.",
    "Refuse to guess PPE or to clean up a spill beyond your training.",
  ],
  sources: [SOURCES.pictograms, SOURCES.labels, SOURCES.sds, SOURCES.whmisSuppliers, SOURCES.albertaOhs],
  blocks: [
    {
      type: "symbols",
      id: "whmis-symbols",
      phase: "learn",
      xpKind: "lesson",
      title: "The symbols",
      intro:
        "Tap a pictogram. The symbol gets your attention. The label and the SDS tell you what to do. The environmental pictogram is not required by WHMIS, though you may still see it. Some hazard classes do not use a pictogram at all, and the label can still show a signal word and statements.",
      cards: [
        {
          id: "flame",
          glyph: "flame",
          name: "Flame",
          meaning: "Fire hazards. CCOHS lists classes such as flammable gases, aerosols, liquids and solids, and some self-reactive, pyrophoric, self-heating, organic peroxide, and chemicals-under-pressure categories.",
          siteExample: "Solvent adhesive, gasoline, and some aerosols on a finishing crew.",
          action: "Keep ignition sources away, as the label states. Read the SDS before you store or use it.",
        },
        {
          id: "oxidizer",
          glyph: "flame-circle",
          name: "Flame over circle",
          meaning: "Oxidizing hazards. These products can cause or intensify a fire.",
          siteExample: "Some oxidizers used in specialty work. Oxygen gas itself is usually the gas-cylinder pictogram, not this one. Check the label.",
          action: "Keep it away from combustibles and from the products the SDS calls incompatible.",
        },
        {
          id: "bomb",
          glyph: "bomb",
          name: "Exploding bomb",
          meaning: "Severe explosion or reactivity hazards, including some organic peroxides and self-reactive products.",
          siteExample: "Uncommon on many building sites, and still a symbol you stop for.",
          action: "Do not handle it on a hunch. Get the SDS and the site procedure.",
        },
        {
          id: "corrosion",
          glyph: "corrosion",
          name: "Corrosion",
          meaning: "Serious eye damage, skin corrosion, or corrosive to metals.",
          siteExample: "Cement and some masonry cleaners. Wet cement is a construction classic.",
          action: "Protect eyes and skin the way the SDS says, and don’t store it where a leak eats the shelf or a drain.",
        },
        {
          id: "cylinder",
          glyph: "cylinder",
          name: "Gas cylinder",
          meaning: "Gases under pressure, and chemicals under pressure.",
          siteExample: "Propane, oxygen, and other compressed gases.",
          action: "Caps on when they move, secured so they cannot fall, and away from the heat the label names.",
        },
        {
          id: "skull",
          glyph: "skull",
          name: "Skull and crossbones",
          meaning: "Acute toxicity that can be fatal or toxic.",
          siteExample: "Some highly toxic products. The pictogram is the alarm, not the dose.",
          action: "Do not open, sniff, or “try a little.” Use the SDS and stay out unless you are trained for that task.",
        },
        {
          id: "health",
          glyph: "health",
          name: "Health hazard",
          meaning: "Serious longer-term health hazards. CCOHS includes carcinogenicity, respiratory sensitization, reproductive toxicity, specific target-organ toxicity, germ-cell mutagenicity, and aspiration hazard.",
          siteExample: "Products that contain crystalline silica, or other products classified for those health effects.",
          action: "Control the dust or other exposure. A pictogram does not tell you the exposure limit. The SDS and the site procedure do.",
        },
        {
          id: "exclamation",
          glyph: "exclamation",
          name: "Exclamation mark",
          meaning: "Hazards such as skin or eye irritation, skin sensitization, harmful acute toxicity, and specific target-organ effects such as drowsiness or respiratory irritation.",
          siteExample: "Many adhesives, sealants, and irritant cleaners.",
          action: "Still read the label. “Only an exclamation mark” is not permission to skip gloves or the SDS.",
        },
        {
          id: "bio",
          glyph: "biohazard",
          name: "Biohazardous infectious materials",
          meaning: "Organisms or toxins that can cause disease in people or animals.",
          siteExample: "Uncommon in general building work. More plausible in some demolition or waste jobs.",
          action: "Stop and get instruction. Do not open a container because the work order said “clean the room.”",
        },
      ],
    },
    {
      type: "match",
      id: "whmis-match",
      phase: "practice",
      xpKind: "practice",
      title: "Match the symbol",
      product: "Industrial adhesive",
      brief:
        "Solvent-based adhesive. The training classification says it is a highly flammable liquid and it causes skin irritation. Select every pictogram that fits those two hazards. Leave the others.",
      options: [
        { id: "flame", name: "Flame", glyph: "flame", correct: true },
        { id: "exclamation", name: "Exclamation mark", glyph: "exclamation", correct: true },
        { id: "skull", name: "Skull and crossbones", glyph: "skull", correct: false },
        { id: "cylinder", name: "Gas cylinder", glyph: "cylinder", correct: false },
        { id: "corrosion", name: "Corrosion", glyph: "corrosion", correct: false },
        { id: "health", name: "Health hazard", glyph: "health", correct: false },
      ],
      success: "Flame for the flammable liquid. Exclamation mark for the skin irritation described here. This training label does not claim acute fatal toxicity, compressed gas, corrosion, or the health-hazard classes.",
      miss: "Match the words in the brief. Flammable liquid points to the flame. Skin irritation, as described here, points to the exclamation mark. Extra pictograms invent a classification this product was not given.",
    },
    {
      type: "label",
      id: "whmis-label",
      phase: "practice",
      xpKind: "practice",
      title: "Label detective",
      intro:
        "This is a fictional supplier label for training. Real supplier labels are in English and French. Find each element. First tap counts.",
      prompts: [
        {
          id: "find-id",
          ask: "Find the product identifier.",
          zoneId: "identifier",
          success: "The product identifier is the name you use to match this container to the SDS.",
        },
        {
          id: "find-picto",
          ask: "Find a hazard pictogram.",
          zoneId: "pictogram",
          success: "The pictogram is the symbol inside the red diamond. It signals the type of hazard. It does not replace the statements.",
        },
        {
          id: "find-signal",
          ask: "Find the signal word.",
          zoneId: "signal",
          success: "Correct. The signal word communicates the relative level of hazard. WHMIS uses Danger or Warning. Danger is the stronger of the two.",
        },
        {
          id: "find-hazard",
          ask: "Find the hazard statement.",
          zoneId: "hazard",
          success: "Hazard statements describe the nature of the hazard in standard phrases.",
        },
        {
          id: "find-precaution",
          ask: "Find the precautionary information.",
          zoneId: "precaution",
          success: "Precautionary statements tell you how to prevent or reduce harm: storage, PPE, and what to do if something goes wrong.",
        },
        {
          id: "find-supplier",
          ask: "Find the supplier information.",
          zoneId: "supplier",
          success: "Supplier information tells you who put the product into the Canadian marketplace. You can match questions back to them through your employer. This name is fictional.",
        },
      ],
      zones: [
        { id: "identifier", label: "Northline Contact Adhesive NL-14", x: 8, y: 8, w: 70, h: 12 },
        { id: "pictogram", label: "Pictogram", x: 78, y: 24, w: 16, h: 22 },
        { id: "signal", label: "DANGER", x: 8, y: 24, w: 40, h: 12 },
        { id: "hazard", label: "Hazard statements", x: 8, y: 40, w: 84, h: 16 },
        { id: "precaution", label: "Precautionary statements", x: 8, y: 58, w: 84, h: 18 },
        { id: "supplier", label: "Supplier", x: 8, y: 80, w: 84, h: 14 },
      ],
    },
    {
      type: "sds",
      id: "whmis-sds",
      phase: "play",
      xpKind: "game",
      title: "SDS search",
      mission:
        "You spilled a chemical and need to know what protective equipment and emergency measures apply. You are a safe distance away. Find the section. You do not need to memorize all sixteen.",
      sections: [
        { num: 1, title: "Identification", body: "Product name: Northline Contact Adhesive NL-14. Fictional supplier and emergency phone. Use this section to confirm you have the right sheet." },
        { num: 2, title: "Hazard identification", body: "Classification, pictograms, signal word DANGER, hazard statements, and precautionary statements. This is the label information, expanded." },
        { num: 3, title: "Composition", body: "Ingredients. Some names may be withheld under confidential-business rules. This is not the spill procedure." },
        { num: 4, title: "First-aid measures", body: "What to do for inhalation, skin, eyes, and ingestion, plus symptoms and any immediate medical notes. Training text only." },
        { num: 5, title: "Fire-fighting measures", body: "Suitable extinguishing media and hazards if it burns. For the fire crew and the site plan, not a reason to stay in the smoke." },
        { num: 6, title: "Accidental release measures", body: "Personal precautions, protective equipment, and emergency procedures for a spill, plus methods for containment and cleanup. This is the section for “what do we do about the spill?”" },
        { num: 7, title: "Handling and storage", body: "How to handle it and what not to store it beside. Useful before the spill, and still useful after." },
        { num: 8, title: "Exposure controls / personal protection", body: "Exposure limits, engineering controls, and the PPE. This is where you look for gloves, eye protection, and whether a respirator is specified." },
        { num: 9, title: "Physical and chemical properties", body: "Appearance, odour, flash point, and similar facts. Not the first stop in a spill." },
        { num: 10, title: "Stability and reactivity", body: "Conditions and materials to avoid. Check it when you are storing, not when you are standing in the product." },
        { num: 11, title: "Toxicological information", body: "Health effects and routes of exposure. Important, and not a cleanup method." },
        { num: 12, title: "Ecological information", body: "Environmental effects. Not the worker PPE section." },
        { num: 13, title: "Disposal considerations", body: "Disposal. Follow the site and local rules. Do not pour it out to “empty the drum.”" },
        { num: 14, title: "Transport information", body: "Shipping information. Relevant when it is on the road, not for this spill on the slab." },
        { num: 15, title: "Regulatory information", body: "Safety, health, and environmental regulations specific to the product." },
        { num: 16, title: "Other information", body: "The date the SDS was prepared or last revised. An old sheet is a reason to ask for the current one." },
      ],
      questions: [
        {
          id: "sds-spill",
          ask: "Where would you look for spill emergency measures?",
          section: 6,
          explain: "Section 6, Accidental release measures. That is the spill section. You still follow the site emergency plan and your level of training.",
        },
        {
          id: "sds-ppe",
          ask: "Where would you look for the protective equipment?",
          section: 8,
          explain: "Section 8, Exposure controls / personal protection. PPE for the product lives here, along with engineering controls.",
        },
        {
          id: "sds-first",
          ask: "A coworker got product on their skin. Which section describes first aid?",
          section: 4,
          explain: "Section 4, First-aid measures. Then you follow the site’s emergency process, including who calls for help.",
        },
        {
          id: "sds-name",
          ask: "You want to confirm this sheet matches the container. Where is the product identifier?",
          section: 1,
          explain: "Section 1, Identification. Match the name on the container to the name on the sheet before you trust the rest.",
        },
      ],
    },
    {
      type: "hazard-hunt",
      id: "whmis-storage",
      phase: "play",
      xpKind: "game",
      title: "Chemical storage",
      intro: "The supply cage. Report each storage problem. Clear areas will say “no hazard here.”",
      scene: "cage",
      hazards: storageHazards,
      decoys: [
        {
          id: "cabinet-ok",
          kind: "cabinet",
          x: 12,
          y: 70,
          label: "Closed, labelled cabinet",
          feedback: "No hazard here. That cabinet is closed, labelled, and not leaking.",
        },
        {
          id: "eyewash",
          kind: "eyewash",
          x: 90,
          y: 72,
          label: "Eyewash kept clear",
          feedback: "No hazard here. The eyewash is clear and signed. The problem is the spill in the aisle, not the eyewash.",
        },
      ],
    },
    {
      type: "dialogue",
      id: "whmis-coworker",
      phase: "play",
      xpKind: "game",
      speaker: "Alex",
      line: "I’ve never used this product before. Can you show me where the precautions are?",
      dimension: "communication",
      choices: [
        {
          id: "gloves",
          label: "Just wear gloves.",
          correct: false,
          feedback: "“Gloves” does not say which gloves, and it skips eyes, ventilation, and anything else the sheet names.",
        },
        {
          id: "check",
          label: "Check the label, the SDS, and the workplace procedure.",
          correct: true,
          feedback: "Product-specific information gets checked. You can look it up together. Guessing is how the wrong glove gets used.",
        },
        {
          id: "ask",
          label: "Ask someone who has used it, and skip the sheet.",
          correct: false,
          feedback: "A coworker’s memory can help you find the sheet. It does not replace the sheet.",
        },
        {
          id: "fine",
          label: "It’s probably fine.",
          correct: false,
          feedback: "“Probably” is not a hazard assessment.",
        },
      ],
    },
    {
      type: "choice-set",
      id: "whmis-check",
      phase: "test",
      xpKind: "check",
      title: "Knowledge check",
      items: [
        {
          id: "signal-word",
          prompt: "Which statement about signal words is accurate?",
          dimension: "knowledge",
          options: [
            {
              id: "two",
              label: "WHMIS uses Danger or Warning. Danger signals the more severe hazard.",
              correct: true,
              feedback: "Two signal words. Danger is for the higher hazard. Some classes do not use a signal word at all.",
            },
            {
              id: "many",
              label: "There is a different signal word for every pictogram.",
              correct: false,
              feedback: "Pictograms and signal words do different jobs. The signal words are Danger and Warning.",
            },
            {
              id: "optional",
              label: "Signal words are optional decoration.",
              correct: false,
              feedback: "If a signal word is assigned, it belongs on the label and in section 2 of the SDS.",
            },
          ],
        },
        {
          id: "education-vs-training",
          prompt: "You finished this module. What is still true on a real site?",
          dimension: "procedure",
          options: [
            {
              id: "done",
              label: "Your employer’s WHMIS duty is finished because you played this module.",
              correct: false,
              feedback: "Employers still need a WHMIS program, including education and training on the products people actually use.",
            },
            {
              id: "site",
              label: "You still need the employer’s WHMIS education and training on the products at that workplace.",
              correct: true,
              feedback: "This path is general education. Site products, workplace labels, and the employer’s program are additional.",
            },
            {
              id: "badge",
              label: "The Chemical Detective badge is a WHMIS certificate.",
              correct: false,
              feedback: "The badge means you finished the SITEWISE module. It is not a certificate.",
            },
          ],
        },
      ],
    },
    {
      type: "sequence",
      id: "whmis-incident",
      phase: "test",
      xpKind: "challenge",
      title: "The chemical incident",
      intro:
        "A container is leaking on the fictional yard. Work the sequence. A clock is visible so you can pace yourself. Time does not change your score. Do not take this as training to perform emergency chemical response beyond your job.",
      showTimer: true,
      closing:
        "You recognized it, stayed out of the product, identified it from a safe distance, used the label and SDS, and called the person the site plan names. Cleanup and medical care stay with people trained and assigned to do them.",
      steps: [
        {
          id: "step-back",
          prompt: "You smell a sharp solvent odour and see a wet trail leaving a tipped can. What is the first move?",
          dimension: "hazard",
          track: "challenge",
          options: [
            { id: "back", label: "Step out of the vapour and keep other people from walking through it.", correct: true, feedback: "Avoid the exposure first. You cannot read a label with your face in the product." },
            { id: "wipe", label: "Wipe it up before anyone sees it.", correct: false, feedback: "That puts your hands and lungs in an unidentified product." },
            { id: "sniff", label: "Get closer and sniff so you can name it.", correct: false, feedback: "Sniffing is an exposure. The label is how you name it, from a safe distance if you can see it." },
          ],
        },
        {
          id: "identify",
          prompt: "From the doorway you can see a label: Northline Contact Adhesive NL-14, with a flame pictogram and the signal word DANGER.",
          dimension: "knowledge",
          track: "challenge",
          options: [
            { id: "name", label: "Use that name to find the matching SDS. Do not re-enter the spill to turn the can.", correct: true, feedback: "The product identifier links the can to the sheet. You already have it. Don’t wade in for a better photo." },
            { id: "ignore-label", label: "Ignore the label and treat every spill as water.", correct: false, feedback: "The label is telling you it is a flammable adhesive. Treating it as water is how it spreads and finds an ignition source." },
            { id: "kick", label: "Kick the can upright and then go find the SDS.", correct: false, feedback: "Kicking it can splash you and is not part of your training." },
          ],
        },
        {
          id: "sheet",
          prompt: "You have the SDS at the station, outside the spill. You need the spill measures and the protective equipment. What do you open?",
          dimension: "procedure",
          track: "challenge",
          options: [
            { id: "six-eight", label: "The accidental-release measures and the exposure controls / PPE, then follow the site plan.", correct: true, feedback: "Those headings answer this moment. The site emergency plan still decides who does the cleanup." },
            { id: "sixteen", label: "Only the revision date.", correct: false, feedback: "The date matters if you suspect an old sheet. It does not tell you how to handle the spill." },
            { id: "none", label: "Skip the SDS. You saw the pictogram.", correct: false, feedback: "The pictogram started the story. The release measures and the PPE section continue it." },
          ],
        },
        {
          id: "notify",
          prompt: "Who gets told, and what do you do with the aisle?",
          dimension: "communication",
          track: "challenge",
          options: [
            { id: "super", label: "Tell the supervisor or the person the site plan names, and keep people out.", correct: true, feedback: "Notification and exclusion. You do not become the spill team by being first on scene." },
            { id: "lunch", label: "Mention it at lunch if it is still there.", correct: false, feedback: "A spreading flammable spill does not wait for lunch." },
            { id: "hero", label: "Send the newest worker in with a rag so you can tell the supervisor it’s already done.", correct: false, feedback: "That exposes the person with the least product knowledge. Don’t do it." },
          ],
        },
      ],
    },
  ],
};
