export interface LockerEntry {
  id: string;
  group: "PPE" | "Tools";
  name: string;
  what: string;
  when: string;
  hazard: string;
  inspect: string;
  authorization: string;
  limit: string;
  check: { prompt: string; correct: string; wrong: string };
}

export const LOCKER: LockerEntry[] = [
  {
    id: "hardhat",
    group: "PPE",
    name: "Hard hat",
    what: "Head protection rated for the site.",
    when: "In the work area, unless the site says a zone is clear.",
    hazard: "Falling and struck-by objects.",
    inspect: "Shell, suspension, and cracks. A cracked shell comes out of service.",
    authorization: "Wearing one here does not authorize you for the task.",
    limit: "It does not stop a fall from height.",
    check: { prompt: "The shell is cracked. What do you do?", correct: "Take it out of service.", wrong: "Wear it for one more hour." },
  },
  {
    id: "eyes",
    group: "PPE",
    name: "Eye protection",
    what: "Safety glasses, goggles, or a face shield matched to the task.",
    when: "Cutting, grinding, chemicals, and dust.",
    hazard: "Chips, splash, and dust.",
    inspect: "Lenses, frame, and that it actually seals if the task needs a seal.",
    authorization: "The SDS and the site say which kind. Sunglasses are not a substitute.",
    limit: "Glasses are not goggles. Goggles are not a face shield.",
    check: { prompt: "You are cutting concrete. Which eye protection fits better?", correct: "Goggles or a face shield, as the task requires.", wrong: "Street sunglasses." },
  },
  {
    id: "hearing",
    group: "PPE",
    name: "Hearing protection",
    what: "Plugs or muffs for the noise of the tool.",
    when: "Saws, grinders, and other loud tools.",
    hazard: "Noise that damages hearing.",
    inspect: "Clean plugs, intact muffs, a real seal.",
    authorization: "The site’s noise rules still apply.",
    limit: "You may not hear a backup alarm. Look.",
    check: { prompt: "Muffs are on and a truck is backing up. What changes?", correct: "You look, because you may not hear the alarm.", wrong: "You trust the muffs and keep your back to the truck." },
  },
  {
    id: "gloves",
    group: "PPE",
    name: "Gloves",
    what: "Hand protection matched to the hazard.",
    when: "Cuts, chemicals, heat, or abrasion.",
    hazard: "The specific hazard, not “hands” in general.",
    inspect: "Holes, the right material, and a fit that is not sloppy near a drill.",
    authorization: "A chemical glove is chosen from the SDS, not from the nearest box.",
    limit: "The wrong glove can hold a chemical against the skin.",
    check: { prompt: "You are transferring solvent adhesive. Which glove?", correct: "The chemical-resistant glove the SDS calls for.", wrong: "The cotton work glove." },
  },
  {
    id: "boots",
    group: "PPE",
    name: "Safety footwear",
    what: "Boots with the protection the site requires.",
    when: "On the ground in the work area.",
    hazard: "Crush, puncture, and slips.",
    inspect: "Tread, toe, and that they are the pair the site asked for.",
    authorization: "Boots do not authorize a machine.",
    limit: "They do not protect you from a fall off a roof.",
    check: { prompt: "The tread is smooth and the site is wet. What do you do?", correct: "Change to footwear with tread, or stay off the slick until you can.", wrong: "Walk it. Boots are boots." },
  },
  {
    id: "hivis",
    group: "PPE",
    name: "High-visibility clothing",
    what: "A vest or clothing operators can see.",
    when: "Near vehicles and equipment.",
    hazard: "Struck-by mobile equipment.",
    inspect: "Reflective bands still reflective, vest closed.",
    authorization: "A vest is not permission to stand in a swing radius.",
    limit: "It does not stop a truck. You still stay out of the path.",
    check: { prompt: "You have a vest on and you need to cross behind a truck. What first?", correct: "Eye contact with the operator or a spotter, and a clear path.", wrong: "Walk it. The vest is enough." },
  },
  {
    id: "harness",
    group: "PPE",
    name: "Fall-arrest harness",
    what: "Personal fall-arrest equipment.",
    when: "When a higher control is not in place and the site has a system for you to use.",
    hazard: "A fall.",
    inspect: "Webbing, stitching, hardware, and the anchor you were told to use.",
    authorization: "Hands-on instruction and authorization may be required. This screen is not that instruction.",
    limit: "A harness needs an anchor, clearance, and a rescue plan. Clipping to a random pipe is not a system.",
    check: { prompt: "There is no rated anchor. What do you do?", correct: "Do not clip in and invent one. Stop and use the site’s fall plan.", wrong: "Clip to the nearest pipe and climb." },
  },
  {
    id: "respirator",
    group: "PPE",
    name: "Respiratory protection",
    what: "A respirator matched to the dust or vapour.",
    when: "The task or the SDS calls for one, such as concrete cutting dust.",
    hazard: "Airborne dust or vapour.",
    inspect: "Straps, valves, and the filter the task needs. A dusty filter is not automatically the right filter.",
    authorization: "Fit and medical requirements can apply on a real site. This app does not fit-test you.",
    limit: "The wrong cartridge does not filter the hazard in front of you.",
    check: { prompt: "You are about to dry-cut concrete with no respirator. What do you do?", correct: "Stop. Use the protection the task requires, including the respirator.", wrong: "Hold your breath on the dusty passes." },
  },
  {
    id: "drill",
    group: "Tools",
    name: "Drill",
    what: "A powered drill.",
    when: "Holes the task actually calls for.",
    hazard: "Bit bind, entanglement, and dust.",
    inspect: "Cord or battery, chuck, housing, and the bit.",
    authorization: "Your employer decides who may use it. Selecting it here does not authorize you.",
    limit: "A drill is not a mixer, a grinder, or a lever.",
    check: { prompt: "The cord jacket is cut. What do you do?", correct: "Take the drill out of service.", wrong: "Tape it and finish the holes." },
  },
  {
    id: "grinder",
    group: "Tools",
    name: "Grinder",
    what: "A handheld grinder.",
    when: "The cut or grind the task specifies, with the guard on.",
    hazard: "Wheel failure, sparks, and eye injury.",
    inspect: "Guard, wheel, flanges, and the cord or battery.",
    authorization: "Guard off is not a setup. Authorization is the employer’s, not this screen.",
    limit: "Taking the guard off to “reach” is how the wheel meets a hand.",
    check: { prompt: "The guard will not sit on the housing. What do you do?", correct: "Stop. The grinder stays down.", wrong: "Run it without the guard for this one cut." },
  },
  {
    id: "saw",
    group: "Tools",
    name: "Circular saw",
    what: "A saw for the cut it was built for.",
    when: "With the guard working and the work supported.",
    hazard: "The blade, kickback, and dust.",
    inspect: "Guard return, blade, cord, and the shoe.",
    authorization: "This locker does not authorize the saw.",
    limit: "A free hand is not a clamp.",
    check: { prompt: "The guard sticks open. What do you do?", correct: "Take the saw out of service.", wrong: "Wedge the guard open so it stays out of the way." },
  },
  {
    id: "ladder",
    group: "Tools",
    name: "Ladder",
    what: "A portable ladder.",
    when: "Short access, set on firm clear ground.",
    hazard: "Falls from a bad set, a broken rail, or overreach.",
    inspect: "Rails, rungs, feet, and the labels.",
    authorization: "Hands-on instruction may be required. This page is not that class.",
    limit: "A ladder is not a scaffold and not a work platform for a long task.",
    check: { prompt: "A rail is cracked. What do you do?", correct: "Tag it out and use another way up.", wrong: "Climb the good side." },
  },
  {
    id: "cord",
    group: "Tools",
    name: "Extension cord",
    what: "A cord rated for the tool and the site.",
    when: "Temporary power, off the walkway.",
    hazard: "Shock, trip, and a cut jacket.",
    inspect: "Jacket, ends, and that it is not through water.",
    authorization: "A damaged cord is out of service. You do not repair it with tape unless the site’s qualified person says so.",
    limit: "It is not a permanent circuit.",
    check: { prompt: "The jacket is cut and copper shows. What do you do?", correct: "Remove it from service.", wrong: "Tape the copper and keep the saw running." },
  },
  {
    id: "hand",
    group: "Tools",
    name: "Hand tools",
    what: "Hammers, cutters, and wrenches.",
    when: "The job the tool was made for.",
    hazard: "A mushroomed head, a sprung jaw, or a tool falling from a height.",
    inspect: "Handle, head, and that it is the right tool.",
    authorization: "A hand tool still comes out of service when it is damaged.",
    limit: "A wrench is not a hammer.",
    check: { prompt: "The hammer handle is split. What do you do?", correct: "Set it aside and get another.", wrong: "Tape the handle and keep striking." },
  },
];
